DjangoChaosTheory/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings 
from articles import views as article_view 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', article_view.article_list, name ='home'),
    path('articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import include, path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name ='logout'),
]

articles/urls.py
from django.urls import include, path
from . import views

app_name = 'articles'

urlpatterns = [
        path('', views.article_list, name= 'list'),
        path('create/', views.article_create, name="create"),
        path('<slug:slug>/', views.article_detail, name= 'detail'),  #capturing the slug we in the article in order to display it
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.ImageField(default ='defaultt.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default = None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] +'...' #snip the article body

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article #defining our form and the fields 
        fields = ['title', 'body', 'slug', 'thumb']

DjangoChaosTheory/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST) #validating the data from the login
        if form.is_valid():
            #log in the user
            user = form.get_user() #retrieve the user
            login(request, user) #and log the this user in
            if'next' in request.POST: #get the 'next' input and redirect it
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html',{'articles':articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #save article to DataBase
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Log in</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}  <!-- sending tolken to the server, to ensure that the data is comming from the application -->
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Sign up</h1>
<form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}  <!-- sending tolken to the server, to ensure that the data is comming from the application -->
    {{ form }}
    <input type="submit" value="Signup">
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %} <!-- security measure to prevent requests from other websites sending to our server -->
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%} 

{% block content %} 
<div class="article_detail">
    <div class="article">
        <img src="{{article.thumb.url}}"/>
        <h2>{{article.title}}</h2>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
        <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-width="" data-numposts="5"></div>
    </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
 {% extends 'base_layout.html'%} 

 {% block content %}     
  <h1> Article List</h1>
    <div class="articles">
       {% for article in articles %}
            <div class = 'article'>
                    <h2><a href="{% url 'articles:detail' slug=article.slug  %}">{{article.title}}</a></h2>
                    <p>{{article.snippet}}</p>
                    <p>{{article.date}}</p>
                    <p class="author">added by {{article.author.username}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1> About us</h1>
        <p>We are team Chaos</p>
    </body>
</html>

templates/base_layout.html
{% load static%}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'style.css'%}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home'%}"><img src="{% static 'ctlogo.png' %}" alt="chaostheory"/></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method ="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0"></script>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1> This is the Homepage</h1>
        <p>Welcome to ChaosTheory</p>
    </body>
</html>